apiVersion: v1
kind: Service
metadata:
  name: financialapi-np-srv
spec:
  type: NodePort
  selector:
    app: financialapi
  ports:
    - name: financialapi-np
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30601
    - name: financialapi-log-port
      protocol: TCP
      port: 7120
      targetPort: 7120
      nodePort: 30611
