apiVersion: apps/v1
kind: Deployment
metadata:
  name: financialapi-depl
spec:
  selector:
    matchLabels:
      app: financialapi
  template:
    metadata:
      labels:
        app: financialapi
    spec:
      containers:
        - name: financialapi
          image: mahdib619/financialapi:latest
        - name: financialapi-seq
          image: datalust/seq:2023.1
          ports:
            - containerPort: 7120
          env:
            - name: SEQ_API_LISTENURIS
              value: http://0.0.0.0:7120
            - name: ACCEPT_EULA
              value: "Y"
            - name: SEQ_FIRSTRUN_ADMINPASSWORDHASH
              valueFrom:
                secretKeyRef:
                  name: seq-financial
                  key: ADMIN_PASS
          volumeMounts:
            - mountPath: /data
              name: fncseqdata
      volumes:
        - name: fncseqdata
          persistentVolumeClaim:
            claimName: fncseq-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: financialapi-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: financialapi
  ports:
    - name: financialapi-clusterip
      protocol: TCP
      port: 80
      targetPort: 80
