apiVersion: apps/v1
kind: Deployment
metadata:
  name: universityapi-depl
spec:
  replicas: 1
  selector:
   matchLabels:
     app: universityapi
  template:
    metadata:
      labels:
        app: universityapi
    spec:
      containers:
        - name: universityapi
          image: mahdib619/universityapi:latest
        - name: universityapi-seq
          image: datalust/seq:2023.1
          ports:
            - containerPort: 7120
          env:
            - name: SEQ_API_LISTENURIS
              value: http://0.0.0.0:7120
            - name: ACCEPT_EULA
              value: "Y"
            - name: SEQ_FIRSTRUN_ADMINPASSWORDHASH
              valueFrom:
                secretKeyRef:
                  name: seq-university
                  key: ADMIN_PASS
          volumeMounts:
            - mountPath: /data
              name: uniseqdata
      volumes:
        - name: uniseqdata
          persistentVolumeClaim:
            claimName: uniapiseq-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: universityapi-clusturip-srv
spec:
  type: ClusterIP
  selector:
   app: universityapi
  ports:
   - name: universityapi-clusturip
     protocol: TCP
     port: 80
     targetPort: 80
