apiVersion: v1
kind: Service
metadata:
  name: universityapi-np-srv
spec:
  type: NodePort
  selector:
    app: universityapi
  ports:
    - name: universityapi-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30600
    - name: universityapi-log-port
      protocol: TCP
      port: 7120
      targetPort: 7120
      nodePort: 30610
